# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [6]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
import pandas as pd
company_df = pd.read_csv(url)
company_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [7]:
company_df.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [13]:
company_df.columns = [column.lower().replace(" ", "_") for column in company_df.columns]
company_df.columns

Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

In [15]:
company_df = company_df.rename(columns={"st": "state"})
company_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [22]:
company_df["gender"].unique()
company_df["gender"] = company_df["gender"].replace({"Femal":"F", "female":"F", "Male":"M"})
company_df["gender"]

0       NaN
1         F
2         F
3         M
4         M
       ...
4003    NaN
4004    NaN
4005    NaN
4006    NaN
4007    NaN
Name: gender, Length: 4008, dtype: str

In [28]:
company_df["state"].unique()
company_df["state"] = company_df["state"].replace({"Cali":"California", "AZ":"Arizona", "WA":"Washington"})
company_df["state"].unique()

<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan]
Length: 6, dtype: str

In [29]:
company_df["education"].unique()
company_df["education"] = company_df["education"].replace({"Bachelors":"Bachelor"})
company_df["education"].unique()

<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor', nan]
Length: 6, dtype: str

In [30]:
company_df["customer_lifetime_value"].head()

0            NaN
1     697953.59%
2    1288743.17%
3     764586.18%
4     536307.65%
Name: customer_lifetime_value, dtype: str

In [35]:
company_df["customer_lifetime_value"] = company_df["customer_lifetime_value"].str.replace("%", "")
company_df["customer_lifetime_value"]

0              NaN
1        697953.59
2       1288743.17
3        764586.18
4        536307.65
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: customer_lifetime_value, Length: 4008, dtype: str

In [32]:
company_df["vehicle_class"].unique()
company_df["vehicle_class"] = company_df["vehicle_class"].replace({"Sports Car":"Luxury", "Luxury SUV":"Luxury", "Luxury Car":"Luxury"})
company_df["vehicle_class"].unique()

<ArrowStringArray>
['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan]
Length: 5, dtype: str

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [36]:
company_df["customer_lifetime_value"] = company_df["customer_lifetime_value"].astype(float)
company_df["customer_lifetime_value"].dtype

dtype('float64')

In [37]:
company_df["number_of_open_complaints"].unique()

<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [44]:
def extract_complaints(value):
    try:
        parts = value.split("/")
        return parts[1]
    except AttributeError:
        return value

company_df["number_of_open_complaints"] = (company_df["number_of_open_complaints"].apply(extract_complaints))
company_df["number_of_open_complaints"].unique()

array([<function extract_complaints at 0x000001DD777664B0>], dtype=object)

In [46]:
original_df = pd.read_csv(url)

company_df["number_of_open_complaints"] = original_df["Number of Open Complaints"]

print(company_df["number_of_open_complaints"].unique())

<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [47]:
company_df["number_of_open_complaints"] = (company_df["number_of_open_complaints"].apply(extract_complaints))

print(company_df["number_of_open_complaints"].unique())

<ArrowStringArray>
['0', '2', '1', '3', '5', '4', nan]
Length: 7, dtype: str

In [48]:
company_df["number_of_open_complaints"] = (company_df["number_of_open_complaints"].astype(float))

company_df["number_of_open_complaints"].dtype

dtype('float64')

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [50]:
company_df.isna().sum()

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [51]:
company_df = company_df.dropna(how="all")
company_df.isna().sum()

customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [60]:
cclv_median = company_df["customer_lifetime_value"].median()

company_df["customer_lifetime_value"] = company_df["customer_lifetime_value"].fillna(clv_median)

print(company_df["customer_lifetime_value"].isna().sum())

0

In [59]:
clv_median = company_df["customer_lifetime_value"].median()
company_df["customer_lifetime_value"].isna().sum()

np.int64(3)

In [61]:
company_df.isna().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [62]:
numeric_columns = company_df.select_dtypes(include="number").columns

print(numeric_columns)

Index(['customer_lifetime_value', 'income', 'monthly_premium_auto',
       'number_of_open_complaints', 'total_claim_amount'],
      dtype='str')

In [63]:
for column in numeric_columns:
    company_df[column] = company_df[column].astype(int)
company_df.dtypes

customer                       str
state                          str
gender                         str
education                      str
customer_lifetime_value      int64
income                       int64
monthly_premium_auto         int64
number_of_open_complaints    int64
policy_type                    str
vehicle_class                  str
total_claim_amount           int64
dtype: object

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [64]:
company_df.duplicated().sum()

np.int64(0)

In [65]:
company_df = company_df.reset_index(drop=True)

company_df.to_csv("company_cleaned.csv", index=False)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [4]:
import cleaning

print(cleaning.clean_data)

<function clean_data at 0x000001BE0F143740>

In [5]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

company_df = pd.read_csv(url)

company_df = cleaning.clean_data(company_df)

company_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Unknown,Master,588174,0,1000,0,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,F,Bachelor,697953,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586,0,106,0,Corporate Auto,SUV,529
4,GA49547,Washington,M,High School or Below,536307,36357,68,0,Personal Auto,Four-Door Car,17

In [ ]:
print(company_df.isna().sum())
print("Duplicados:", company_df.duplicated().sum())
print(company_df.dtypes)

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [6]:
company_df[["total_claim_amount", "customer_lifetime_value"]].describe()

       total_claim_amount  customer_lifetime_value
count         1071.000000             1.071000e+03
mean           404.528478             7.931141e+05
std            293.041850             6.426676e+05
min              0.000000             2.004350e+05
25%            201.500000             4.048530e+05
50%            354.000000             5.881740e+05
75%            532.000000             8.945205e+05
max           2893.000000             5.816655e+06

In [7]:
claim_limit = company_df["total_claim_amount"].quantile(0.75)

clv_limit = company_df["customer_lifetime_value"].quantile(0.25)

print("Percentil 75 de reclamaciones:", claim_limit)
print("Percentil 25 del valor del cliente:", clv_limit)

Percentil 75 de reclamaciones: 532.0
Percentil 25 del valor del cliente: 404853.0

In [8]:
selected_customers = company_df.loc[(company_df["total_claim_amount"] > claim_limit) & (company_df["customer_lifetime_value"] <= clv_limit)]

selected_customers.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
17,OE15005,California,Unknown,College,394524,28855,101,0,Personal Auto,SUV,647
23,TZ98966,Nevada,Unknown,Bachelor,245019,0,73,3,Corporate Auto,Four-Door Car,554
26,US89481,California,Unknown,Bachelor,394637,0,111,0,Personal Auto,Four-Door Car,799
38,CM61827,Oregon,Unknown,Bachelor,309003,0,90,0,Personal Auto,Two-Door Car,648
42,IL19217,California,Unknown,Bachelor,393900,60021,99,0,Personal Auto,Four-Door Car,882

In [9]:
selected_customers[["total_claim_amount", "customer_lifetime_value"]].describe()

       total_claim_amount  customer_lifetime_value
count           40.000000                40.000000
mean           723.300000            341577.425000
std            149.216449             56921.466178
min            537.000000            228759.000000
25%            632.750000            304220.500000
50%            685.000000            365995.000000
75%            799.000000            387364.000000
max           1185.000000            402381.000000

In [10]:
print("Clientes seleccionados:", selected_customers.shape[0])

Clientes seleccionados: 40